#!/bin/bash

DEV=hw:0
SUDO=""
AMIXER=/usr/bin/amixer

#TODO use hw:3
#${SUDO} ${AMIXER} -D${DEV} sset Capture 9 cap on
#${SUDO} ${AMIXER} -D${DEV} sset Mic 100 cap on

DEV=hw:1

# enable line input
${SUDO} ${AMIXER} -D${DEV} sset Line 128 cap on

# disable mic input
${SUDO} ${AMIXER} -D${DEV} sset Mic 0 off

# playback to controller for testing purposes
${SUDO} ${AMIXER} -D${DEV} sset Line 128

${SUDO} ${AMIXER} -D${DEV} sset 'PCM Capture Source' Line

#${SUDO} ${AMIXER} -D${DEV} sset 'Digital In' off


